name: Auto DC Build

on:
  schedule:
    - cron: 34 */6 * * *
  workflow_dispatch:
    inputs:
      rebuild:
        description: '忽略构建记录以重新构建'
        required: false
        type: boolean
      donotpublish:
        description: '构建后不提交发布新版'
        required: false
        type: boolean

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - userName: wwz09
            repoName: duocangbox
            branchName: main
            diy: wwz09DC.sh
            dcdiy: DCDIY.sh
            java_ver: 11
          - userName: mlabalabala
            repoName: box
            branchName: main
            diy: zyangDC.sh
            dcdiy: DCDIYA.sh
            java_ver: 11
          - userName: gj8438
            repoName: box
            branchName: main
            diy: YYDC.sh
            dcdiy: DCDIY.sh
            java_ver: 11

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          
      - name: 检查新的提交
        run: |
          upStream=https://github.com/${{ matrix.userName }}/${{ matrix.repoName }}
          echo "upStream=$upStream" >> $GITHUB_ENV
          git clone https://github.com/${{ matrix.userName }}/${{ matrix.repoName }} TVBoxOSC
          cd TVBoxOSC
          commit=$(git rev-parse HEAD)
          if ! grep -q "$commit" ../README.md || [ "${{ inputs.rebuild }}" == "true" ]; then
            echo "commit=$commit" >> $GITHUB_ENV
            echo "commitS=${commit:0:7}" >> $GITHUB_ENV
          fi

      - name: 签出源代码
        if: ${{ env.commit }}
        run: |
          cd TVBoxOSC
          git checkout ${{ env.commit }}
          echo "tag=$(git log --date=format:'%Y%m%d-%H%M' --pretty=format:%cd ${{ env.commitS }} -1)" >> $GITHUB_ENV

      - name: DIY 
        if: ${{ env.commit }}
        working-directory: TVBoxOSC
        run: |
          chmod +x ${{ github.workspace }}/DIY/sh/${{ matrix.diy }}
          chmod +x ${{ github.workspace }}/DIY/sh/${{ matrix.dcdiy }}
          bash ${{ github.workspace }}/DIY/sh/${{ matrix.diy }}
          bash ${{ github.workspace }}/DIY/sh/${{ matrix.dcdiy }}
         
      - name: 额外修改
        if: ${{ env.commit }}
        working-directory: TVBoxOSC
        run: |
          echo '修改VersionName'
          sed -i "/versionName/s#[0-9a-zA-Z_\.\'\"-]\+\$#\'${{ env.tag }}\'#" app/build.gradle
          sed -i "/android:text=/s#=\"#=\"${{ env.tag }}\\\\n\\\\n#" app/src/main/res/layout/dialog_about.xml
          echo 'crosswalk源，防挂'
          if grep -q 'crosswalk' build.gradle; then
            sed -i "/crosswalk/a\        maven { url 'https://o0halfLife0o.github.io/crosswalk/releases/crosswalk/android/maven2' }" build.gradle
          else
            sed -i "/jitpack.io/a\        maven { url 'https://o0halfLife0o.github.io/crosswalk/releases/crosswalk/android/maven2' }" build.gradle
          fi
          
      - name: 安卓安装包签名（已修复拼写错误）
        if: ${{ env.commit }}
        working-directory: TVBoxOSC
        run: |
          cat >> app/build.gradle << 'EOF'
          android {
              signingConfigs {
                  if (project.hasProperty("RELEASE_STORE_FILE")) {
                      myConfig {
                          storeFile file(RELEASE_STORE_FILE)
                          storePassword RELEASE_STORE_PASSWORD
                          keyAlias RELEASE_KEY_ALIAS
                          keyPassword RELEASE_KEY_PASSWORD
                          v1SigningEnabled true
                          v2SigningEnabled true
                          enableV3Signing = true
                          enableV4Signing = true
                      }
                  }
              }
              buildTypes {
                  debug {
                      if (project.hasProperty("RELEASE_STORE_FILE")) {
                          signingConfig signingConfigs.myConfig
                      }
                  }
                  release {
                      if (project.hasProperty("RELEASE_STORE_FILE")) {
                          signingConfig signingConfigs.myConfig
                      }
                  }
              }
          }
          EOF
          
          cp -f ${{ github.workspace }}/.github/workflows/TVBoxOSC.jks app/TVBoxOSC.jks
          sed -i '$a\RELEASE_STORE_FILE=./TVBoxOSC.jks'     ./gradle.properties
          sed -i '$a\RELEASE_KEY_ALIAS=TVBoxOSC'            ./gradle.properties
          sed -i '$a\RELEASE_STORE_PASSWORD=TVBoxOSC'       ./gradle.properties
          sed -i '$a\RELEASE_KEY_PASSWORD=TVBoxOSC'         ./gradle.properties

      - uses: actions/setup-java@v5
        if: ${{ matrix.java_ver }}
        with:
          distribution: temurin
          java-version: ${{ matrix.java_ver }}

      - name: 进行构建
        if: ${{ env.commit }}
        working-directory: TVBoxOSC
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --parallel --daemon --warning-mode all

      - name: 准备应用程序
        if: ${{ env.commit }}
        working-directory: TVBoxOSC
        run: |
          rm -rf apk/
          mkdir -p apk/
          apk_files=$(find . -name "*.apk" -type f)
          for file in $apk_files; do
            base=$(basename "$file")
            new_base="${{ matrix.userName }}_${{ matrix.repoName }}_${{ env.tag }}.apk"
            mv "$file" "apk/$new_base"
          done

      - name: Whether Or Not to Publish
        if: ${{ inputs.donotpublish && env.commit }}
        continue-on-error: true
        run: |
          echo "commit=" >> $GITHUB_ENV

      - name: 发布并上传
        uses: ncipollo/release-action@v1
        if: ${{ env.commit }}
        continue-on-error: true
        with:
          name: ${{ matrix.userName }}_${{ matrix.repoName }}_${{ env.tag }}
          tag: ${{ matrix.userName }}_${{ matrix.repoName }}_${{ env.tag }}_${{ env.commitS }}
          allowUpdates: true
          removeArtifacts: true
          artifacts: TVBoxOSC/apk/*.apk

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.0
        with:
          keep_latest: 10
          delete_tags: true
          delete_tag_pattern: ${{ matrix.userName }}_${{ matrix.repoName }}_.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
