name: Check And Clear Cache

on:
  #schedule:
    #- cron: 59 */8 * * *
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
     
            
    steps:
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }} - node - ${{ hashFiles('package.json') }}
