name: Test

on:
  #schedule:
    #- cron: 59 */8 * * *
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
     
            
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check 和 Clear Cache
        run: |
          CACHE_SIZE=$(du -sh /path/to/cache | awk '{print $1}')
          if [ $(echo "$CACHE_SIZE > 10G" | bc -l) -eq 1 ]; then
            # 这里可以添加清理缓存的实际命令，比如删除目录下的旧文件
            find /path/to/cache -type f -ctime +2 -delete
          fi
