name: Clear Gradle Cache Workflow

on:
  workflow_dispatch:

jobs:
  clear-gradle-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 这里可以根据需要设置 Gradle 相关的环境变量等
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          # 例如设置 Gradle 版本
          gradle-version: '7.4' 

      # 清除 Gradle 缓存，这里假设缓存目录在 ~/.gradle/caches
      - name: Clear Gradle Cache
        run: rm -rf ~/.gradle/caches
